# Site settings
title: Stephen Le
description: Physics and mathematics undergraduate
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Stephen Le
user_description: Bio here.
user_title: HEP-ex PhD Candidate
email: pband1256@gmail.com
twitter_username:
github_username:  pband1256
gplus_username:
linkedin_username: hle56

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
